# Generated by Django 2.0 on 2018-02-17 17:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Event Name')),
                ('when', models.DateTimeField(default=datetime.datetime(2018, 3, 7, 18, 7, tzinfo=utc), verbose_name='Event Date/Time')),
                ('when_end', models.DateTimeField(default=datetime.datetime(2018, 3, 7, 18, 7, tzinfo=utc), verbose_name='Event End Date/Time')),
                ('venue', models.CharField(default='TBD', max_length=20, verbose_name='Event Venue')),
                ('tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event Tags (Separate By Comma)')),
                ('desc', models.TextField()),
                ('rules', models.TextField(default='To Be Decided')),
                ('is_team', models.BooleanField()),
                ('image', models.ImageField(upload_to='events/', verbose_name='Event Image')),
                ('type', models.CharField(choices=[('CUL', 'Cultural'), ('TECH', 'Technical')], default='TECH', max_length=10, verbose_name='Event Category')),
                ('prize_amt', models.IntegerField(verbose_name='Prize Amount')),
                ('sec_prize_amt', models.IntegerField(blank=True, null=True, verbose_name='Second Prize Amount')),
                ('reg_cost', models.IntegerField(verbose_name='Registration Cost')),
                ('primary_coord_name', models.CharField(max_length=30, null=True, verbose_name='Primary Coordinator Name')),
                ('primary_coord_contact', phonenumber_field.modelfields.PhoneNumberField(default='+91', max_length=128, null=True, verbose_name='Primary Coordinator Number')),
                ('secondary_coord_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Secondary Coordinator Name')),
                ('secondary_coord_contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+91', max_length=128, null=True, verbose_name='Secondary Coordinator Number')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Participant Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Participant Email')),
                ('college', models.CharField(max_length=50, verbose_name='College Name')),
                ('mob_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Participant Number')),
                ('source', models.CharField(choices=[('web', 'web'), ('android', 'android')], max_length=10, verbose_name='Registration Source')),
                ('time_registered', models.DateField(auto_now_add=True, verbose_name='Registration Time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aybackend.Event', verbose_name='Event')),
            ],
        ),
    ]
