# Generated by Django 2.0 on 2018-02-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aybackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_flagship',
            field=models.BooleanField(default=False),
        ),
    ]
