# Generated by Django 2.0 on 2018-03-05 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aybackend', '0002_event_is_flagship'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alter_end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 0, 0), verbose_name='Event End Date/Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='alter_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 8, 0, 0), verbose_name='Event Date/Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='coord_id',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Firebase UID For Coordinator'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_alt_time',
            field=models.BooleanField(default=False),
        ),
    ]
